---
- name: Ensure project folder is symlinked for live edits
  file:
    path: "{{ django_project_path }}"
    state: link
    src: "{{ django_project_symlink_dest }}"
  when: django_project_symlink_dest != ""

