---

- name: Ensure that we have a DB
  mysql_db: "name={{ tn2_wp_dbname }}"

- name: Ensure that we have a DB user
  mysql_user:
    name: "{{ django_dbuser }}"
    priv: "{{ tn2_wp_dbname }}.*:ALL,GRANT"
    password: "{{ django_dbpass }}"

- name: Generate WP DB django settings
  template:
    src: wpdb_settings.py
    dest: "{{ django_path }}/wpdb_settings.py"

- name: Symlink local_settings.py into our venv's site-packages
  file:
    path: "{{ django_sitepackages_path }}/wpdb_settings.py"
    state: link
    src: "{{ django_path }}/wpdb_settings.py"
