---
- import_tasks: postgres.yml

- file:
    path: "{{ tn2_log_path|dirname }}"
    state: directory
    mode: "0750"
    owner: "{{ django_user }}"
    group: "www-data"

- file:
    path: "{{ django_path }}"
    state: directory
    mode: "0750"
    owner: "{{ django_user }}"
    group: "www-data"

- name: Run make
  make:
    chdir: "{{ tn2_project_root }}"
    params:
      PREFIX: "{{ django_path }}"
      CONF_PATH: "{{ django_jsonsettings_path }}"
      VENV_ARGS: "--system-site-packages"
      REQUIREMENTS_PATH: "requirements.freeze"
    target: install
  become: yes
  become_user: "{{ django_user }}"
