---
- block:
    - name: Ensure that we have a DB user
      postgresql_user: "name={{ tn2_dbuser }} password={{ tn2_dbpass }} role_attr_flags=CREATEDB"

    - name: Ensure that we have a DB
      postgresql_db: "name={{ tn2_dbname }} owner={{ tn2_dbuser }}"

    - name: Ensure that our user has access to our DB
      postgresql_user: "name={{ tn2_dbuser }} db={{ tn2_dbname }} priv=ALL"

  become: yes
  become_user: postgres
