---
- block:
    - name: Ensure that we have a DB user
      postgresql_user: "name={{ django_dbuser }} password={{ django_dbpass }} role_attr_flags=CREATEDB"

    - name: Ensure that we have a DB
      postgresql_db: "name={{ django_dbname }} owner={{ django_dbuser }}"

    - name: Ensure that our user has access to our DB
      postgresql_user: "name={{ django_dbuser }} db={{ django_dbname }} priv=ALL"

  become: yes
  become_user: postgres
