---
common_extra_packages:
  - python3
  - python3-venv
  - python3-psycopg2
  - python3-pil
  - python3-bs4
  - python3-bleach
  - sassc

nginx_cache_enable: yes

django_name: tn2
django_path: /opt/tn2
django_project_path: "{{ django_path }}/src"
django_src_path: "{{ django_project_path }}"

django_dbname: "{{ django_name }}"
django_dbuser: "{{ django_name }}"

django_env_variables:
  TN2_CONF_PATH: "{{ django_jsonsettings_path }}"

django_jsonsettings_properties:
  project_root: "{{ django_path }}"
  debug: "{{ django_debug|d(False) }}"
  secret_key: "{{ django_secret_key }}"
  media_url: https://images.threadandneedles.org/
  thumbnail_url: https://images.threadandneedles.org/thumb/
  database:
    HOST: localhost
    NAME: "{{ django_dbname }}"
    USER: "{{ django_dbuser }}"
    PASSWORD: "{{ django_dbpass }}"
  allowed_hosts: "['{{ django_domain_name }}', ] + {{ django_extra_domain_names|default([]) }}"
  email: "{% if tn2_smtp is defined %}{{ tn2_smtp }}{% endif %}"
  log_to: "{{ tn2_log_path }}"

django_nginx_locations: |
  location /thumb/ {
    proxy_pass http://{{ nginx_thumbnailer_bind }};
    proxy_cache {{ nginx_cache_name }};
    proxy_cache_valid 200 60m;
  }

nginx_thumbnailer_media_path: "{{ django_path }}/media"

# Where the root of the project source is (that is, the Makefile's directory)
tn2_project_root: /opt/tn2/project
