---
nginx_cache_enable: yes

django_name: tn2
django_path: /opt/tn2
django_project_path: "{{ django_path }}/src"
django_src_path: "{{ django_project_path }}"

django_env_variables:
  TN2_CONF_PATH: "{{ django_jsonsettings_path }}"

django_jsonsettings_properties:
  project_root: "{{ django_path }}"
  debug: "{{ django_debug|d(False) }}"
  secret_key: "{{ django_secret_key }}"
  database:
    NAME: "{{ django_dbname }}"
    USER: "{{ django_dbuser }}"
    PASSWORD: "{{ django_dbpass }}"
  allowed_hosts: "['{{ django_domain_name }}', ] + {{ django_extra_domain_names|default([]) }}"
  email: "{% if tn2_smtp is defined %}{{ tn2_smtp }}{% endif %}"

django_nginx_locations: |
  location /thumb/ {
    proxy_pass http://{{ nginx_thumbnailer_bind }};
    proxy_cache {{ nginx_cache_name }};
    proxy_cache_valid 200 60m;
  }

nginx_thumbnailer_media_path: "{{ django_path }}/media"

tn2_packages:
  - python3
  - python3-psycopg2
  - python3-pil
  - python3-bs4
  - python3-bleach
