---
common_extra_packages:
  - python3-psycopg2
  # for "make watch"
  - entr
  # for pillow + django-simple-captcha
  - libz-dev
  - libjpeg-dev
  - libfreetype6-dev

django_name: tn2

django_env_variables:
  TN2_CONF_PATH: "{{ django_jsonsettings_path }}"

django_jsonsettings_properties:
  project_root: "{{ django_path }}"
  debug: "{{ django_debug }}"
  secret_key: "{{ django_secret_key }}"
  database:
    NAME: "{{ django_dbname }}"
    USER: "{{ django_dbuser }}"
    PASSWORD: "{{ django_dbpass }}"
  allowed_hosts: "['{{ django_domain_name }}', ] + {{ django_extra_domain_names|default([]) }}"
  email: "{% if tn2_smtp is defined %}{{ tn2_smtp }}{% endif %}"
