---
django_user: vagrant
django_domain_name: tn2.local
django_secret_key: whatever
django_dbpass: whatever
django_media_redirect_to: https://www.threadandneedles.fr
nginx_thumbnailer_redirect_to: "{{ django_media_redirect_to }}"
tn2_project_root: /vagrant
