# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0001_squashed_0052_auto_20170212_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
