# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:23
from __future__ import unicode_literals

import os
import shutil

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_initial_data(apps, schema_editor):
    Article = apps.get_model("tn2app", "Article")
    if Article.objects.exists():
        print("There's data in there. Skipping initial data migration")
        return
    FIXTURES = [
        'pages',
        'emails',
        'articlecategory',
        'projectcategory',
        'sample_data',
    ]
    for fixture in FIXTURES:
        call_command('loaddata', fixture, app_label='tn2app')
    fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
    srcpath = os.path.join(fixture_dir, 'media')
    destpath = settings.MEDIA_ROOT
    shutil.rmtree(destpath)
    shutil.copytree(srcpath, destpath)

class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0002_auto_20170219_1850'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
