# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tn2app', '0002_auto_20161031_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
