# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0002_auto_20170219_1850'),
    ]

    operations = [
    ]
