# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0003_discussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
