# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tn2app', '0004_auto_20170221_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='restrict_access_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
