# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0005_auto_20161110_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussiongroup',
            options={'permissions': (('access_private_groups', 'Accéder aux groupes privés'),)},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
