# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0006_auto_20161201_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
