# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tn2app', '0007_discussion_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wpdb_id', models.IntegerField(null=True)),
                ('display_name', models.CharField(max_length=60, blank=True, verbose_name='Pseudo')),
                ('description', models.TextField(blank=True, verbose_name='Qui suis-je?')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Ville')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('skill_level', models.CharField(blank=True, max_length=20, verbose_name='Niveau')),
                ('sewing_machine', models.CharField(blank=True, max_length=60, verbose_name='MAC')),
            ],
        ),
    ]
