# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:54
from __future__ import unicode_literals

from django.db import migrations
import tn2app.util


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0007_auto_20170329_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_post_url',
            field=tn2app.util.PermissiveURLField(blank=True, max_length=250, verbose_name='Article sur mon blog'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern_url',
            field=tn2app.util.PermissiveURLField(blank=True, max_length=250, verbose_name='URL du patron ou tutoriel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='store_url',
            field=tn2app.util.PermissiveURLField(blank=True, max_length=250, verbose_name='URL du produit dans votre boutique'),
        ),
    ]
