# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0009_remove_notification_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Réponse dans une discussion'), (2, 'Vote pour un projet')], db_index=True),
        ),
    ]
