# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0009_auto_20161204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tn2app.models.get_user_avatar_path),
        ),
    ]
