# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tn2app.util


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0010_auto_20170620_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('url', tn2app.util.PermissiveURLField(blank=True, verbose_name='Page web')),
                ('is_free', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatternCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('url', tn2app.util.PermissiveURLField(blank=True, verbose_name='Site web')),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn2app.PatternCreator'),
        ),
    ]
