# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import tn2app.util


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0011_auto_20170701_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={'verbose_name': 'Patron'},
        ),
        migrations.AlterModelOptions(
            name='patterncreator',
            options={'verbose_name': 'Créateur de patrons', 'verbose_name_plural': 'Créateurs de patrons'},
        ),
        migrations.AlterField(
            model_name='pattern',
            name='is_free',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Gratuit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=tn2app.util.PermissiveURLField(blank=True, verbose_name='Site web'),
        ),
    ]
