# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tn2app', '0011_auto_20161207_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', tn2app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='discussiongroup',
            name='description',
            field=models.TextField(),
        ),
    ]
