# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0012_auto_20170701_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ['name'], 'verbose_name': 'Patron'},
        ),
        migrations.AlterModelOptions(
            name='patterncreator',
            options={'ordering': ['name'], 'verbose_name': 'Créateur de patrons', 'verbose_name_plural': 'Créateurs de patrons'},
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='patterncreator',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom'),
        ),
    ]
