# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0012_auto_20161208_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
