# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0013_auto_20161208_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Révision'), (2, 'Publié')], default=0),
        ),
    ]
