# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0014_auto_20161209_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
