# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0015_auto_20170702_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tn2app.PatternCategory', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tn2app.PatternCreator', verbose_name='Créateur'),
        ),
    ]
