# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0016_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='tn2app.ArticleCategory'),
        ),
    ]
