# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0016_auto_20170702_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tn2app.Pattern', verbose_name='Patron'),
        ),
    ]
