# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0017_project_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tn2app.ProjectCategory', verbose_name='Catégorie'),
        ),
    ]
