# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tn2app', '0017_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pattern_name', models.CharField(blank=True, max_length=250)),
                ('pattern_url', models.URLField(blank=True)),
                ('blog_post_url', models.URLField(blank=True)),
                ('store_url', models.URLField(blank=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 1}))),
                ('image2', models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 2}))),
                ('image3', models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 3}))),
                ('image4', models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 4}))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn2app.ProjectCategory'),
        ),
    ]
