# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0018_auto_20161214_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_post_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='store_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
