# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0019_auto_20170706_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tn2app.PatternCategory', verbose_name='Categorie'),
            preserve_default=False,
        ),
    ]
