# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0020_auto_20170706_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='is_jersey',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Maille'),
        ),
    ]
