# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 02:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0020_auto_20161216_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tn2app.models.get_user_avatar_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Qui suis-je?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Grand débutant', 'Grand débutant'), ('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Professionnel', 'Professionnel')], max_length=20, verbose_name='Niveau'),
        ),
    ]
