# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tn2app', '0021_auto_20161218_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn2app.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(through='tn2app.ProjectVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
