# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


def move_legacy_categories(apps, schema_editor):
    Project = apps.get_model('tn2app', 'Project')
    Project.objects.filter(category_id=11).update(category_id=None, target=3)
    Project.objects.filter(category_id=13).update(category_id=None, target=2)
    Project.objects.filter(category_id__in={8, 10}).update(target=4)
    Project.objects.filter(category_id=12).update(category_id=None, domain=2)
    Project.objects.filter(category_id=14).update(category_id=None, domain=4)
    Project.objects.filter(pattern__isnull=True, target__isnull=True).update(target=1)
    Project.objects.filter(pattern__isnull=True, domain__isnull=True).update(domain=1)

class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0021_pattern_is_jersey'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Couture'), (2, 'Tricot'), (3, 'Crochet'), (4, 'Broderie')], db_index=True, null=True, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Femme'), (2, 'Homme'), (3, 'Enfant'), (4, 'Autre')], db_index=True, null=True, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Femme'), (2, 'Homme'), (3, 'Enfant'), (4, 'Autre')], db_index=True, verbose_name='Destinataire'),
        ),
        migrations.RunPython(move_legacy_categories),
    ]
