# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tn2app', '0022_auto_20161219_0114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectvote',
            unique_together=set([('user', 'project')]),
        ),
    ]
