# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0022_auto_20170709_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tn2app.PatternCategory', verbose_name='Catégorie'),
        ),
    ]
