# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0023_auto_20170709_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
