# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0023_auto_20161219_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legacy_like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
