# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0024_delete_projectcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tn2app.PatternCategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Couture'), (2, 'Tricot'), (3, 'Crochet'), (4, 'Broderie')], db_index=True, null=True, verbose_name='Domaine'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Femme'), (2, 'Homme'), (3, 'Enfant'), (4, 'Autre')], db_index=True, null=True, verbose_name='Destinataire'),
        ),
    ]
