# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import functools
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0025_auto_20161220_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_post_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='Article sur mon blog'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn2app.ProjectCategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 1}), verbose_name='Photographie principale du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 2}), verbose_name='Photographie alternative 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 3}), verbose_name='Photographie alternative 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, upload_to=functools.partial(tn2app.models.get_project_image_path, *(), **{'slot': 4}), verbose_name='Photographie alternative 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Patron ou tutoriel utilisé'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL du patron ou tutoriel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='store_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL du produit dans votre boutique'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre du projet'),
        ),
    ]
