# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0026_set_project_category_from_patterns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterncreator',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together=set([('creator', 'name')]),
        ),
    ]
