# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0027_auto_20170711_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='tn2app.PatternCreator', verbose_name='Créateur'),
        ),
    ]
