# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import tn2app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0027_auto_20161222_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tn2app.models.get_group_avatar_path, verbose_name='Avatar'),
        ),
    ]
