# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0028_discussiongroup_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='group_type',
            field=models.SmallIntegerField(choices=[(0, 'Thématique'), (1, 'Géographique'), (2, 'Entraide')], default=0),
        ),
    ]
