# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import tn2app.util


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0028_auto_20170817_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsors')),
                ('url', tn2app.util.PermissiveURLField()),
                ('target', models.PositiveSmallIntegerField(choices=[(0, 'Aucune'), (1, "Page d'accueil"), (2, 'Blog')], db_index=True, verbose_name='Page cible')),
            ],
        ),
    ]
