# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0029_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nom')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Concours',
                'verbose_name_plural': 'Concours',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tn2app.Contest'),
        ),
    ]
