# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0029_discussiongroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='description_short',
            field=models.TextField(blank=True),
        ),
    ]
