# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0030_discussiongroup_description_short'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX tn2app_article_ts1_idx ON tn2app_article USING gin(to_tsvector('french', coalesce(title, '') || ' ' || coalesce(content, '')));",
            "DROP INDEX IF EXISTS tn2app_article_ts1_idx;"
        ),
    ]
