# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0031_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation_time']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='legacy_like_count',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Réponse dans une discussion'), (2, 'Vote pour un projet'), (3, 'Message privé')], db_index=True),
        ),
    ]
