# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0031_article_fulltext_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wpdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
