# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0033_project_fulltext_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX tn2app_discussion_ts1_idx ON tn2app_discussion USING gin(to_tsvector('french', coalesce(title, '') || ' ' || coalesce(content, '')));",
            "DROP INDEX IF EXISTS tn2app_discussion_ts1_idx;"
        ),
    ]
