# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0034_discussion_fulltext_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
