# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0035_auto_20170101_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('contents', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
