# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0036_pagecontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_time',
            field=models.DateTimeField(null=True),
        ),
    ]
