# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0037_project_featured_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Pseudo'),
        ),
    ]
