# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0038_auto_20170107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvote',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
