# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0039_projectvote_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', through='tn2app.ProjectVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
