# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0040_auto_20170107_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvote',
            name='favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
