# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0041_auto_20170107_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
