# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0043_article_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvote',
            name='date_liked',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
