# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0044_auto_20170119_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='display_order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
