# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 20:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0045_discussiongroup_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
