# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:05
from __future__ import unicode_literals

from django.db import migrations


def migrate_comments(apps, schema_editor):
    Comment = apps.get_model('django_comments', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Article = apps.get_model('tn2app', 'Article')
    Project = apps.get_model('tn2app', 'Project')
    Discussion = apps.get_model('tn2app', 'Discussion')
    for target_model in [Article, Project, Discussion]:
        for target in target_model.objects.all():
            target.comments.all().delete()
            ct = ContentType.objects.get_for_model(target)
            comments = Comment.objects.filter(content_type=ct, object_pk=str(target.id))
            print(target._meta.model_name, target.id, comments.count())
            for comment in comments.all():
                target.comments.create(
                    user=comment.user,
                    submit_date=comment.submit_date,
                    comment=comment.comment,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0049_discussioncomment_projectcomment'),
    ]

    operations = [
        migrations.RunPython(migrate_comments),
    ]
