# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn2app', '0051_auto_20170212_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description_for_articles',
            field=models.TextField(blank=True, verbose_name='Description Rédacteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
    ]
