- hosts: all
  vars_files:
    - vars/tn2.yml

  vars:
    django_deployment_type: symlink
    django_project_symlink_dest: "/nomadshare"
    django_domain_name: tn2.local
    django_debug: yes

  roles:
    - common
    - postgres-install
    - nginx
    - django
    - tn2
