- hosts: all
  vars_files:
    - vars/tn2.yml

  vars:
    django_domain_name: tn2.local
    django_secret_key: whatever

  roles:
    - common
    - postgres-install
    - nginx
    - nginx-thumbnailer
    - django
    - tn2

