- hosts: all
  vars_files:
    - vars/tn2.yml

  vars:
    django_domain_name: tn2.local
    django_secret_key: whatever
    django_media_redirect_to: https://www.threadandneedles.fr/media
    tn2_deb_path: /lxdockshare/build/tn2.deb

  roles:
    - common
    - postgres-install
    - nginx
    - nginx-thumbnailer
    - tn2-pre
    - django
    - tn2-post

