- hosts: all
  vars_files:
    - vars/tn2.yml

  vars:
    django_project_symlink_dest: "/nomadshare"
    # Because django_path is a symlink and it doesn't work.
    django_touch_reload_path: "{{ django_src_path }}"
    django_domain_name: tn2.local
    django_debug: yes
    django_secret_key: whatever

  roles:
    - common
    - postgres-install
    - nginx
    - django
    - tn2

